# Generated by Django 5.2.5 on 2025-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('event_id', models.AutoField(help_text='Unique reservation identifier', primary_key=True, serialize=False)),
                ('event_organization', models.TextField(help_text='Organization making the reservation')),
                ('event_type', models.TextField(help_text='Type of event (e.g., conference, workshop, meeting)')),
                ('event_datetime_begin', models.DateTimeField(help_text='Start date and time of the event')),
                ('event_datetime_delta', models.DurationField(help_text='Duration of the event')),
                ('event_area', models.TextField(help_text='Area or room requested for the event')),
                ('event_number_of_people_min', models.PositiveIntegerField(help_text='Minimum estimated number of people')),
                ('event_number_of_people_max', models.PositiveIntegerField(help_text='Maximum estimated number of people')),
                ('event_specialrequests', models.TextField(blank=True, help_text='Any special requests or requirements for the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the reservation', max_length=20)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['event_datetime_begin'],
            },
        ),
    ]
