# Generated by Django 5.2.5 on 2025-08-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('event_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(help_text='Name of the event class/type', max_length=200)),
                ('description', models.TextField(help_text='Description of this event class')),
            ],
            options={
                'verbose_name': 'Event Class',
                'verbose_name_plural': 'Event Classes',
                'ordering': ['event_name'],
            },
        ),
    ]
