# Generated by Django 5.2.5 on 2025-08-17 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(blank=True, help_text='Classification/type of this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventclass'),
        ),
    ]
