# Generated by Django 5.2.5 on 2025-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventclass',
            name='photo1',
            field=models.ImageField(blank=True, help_text='Primary photo for this event class', null=True, upload_to='event_classes/'),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='photo2',
            field=models.ImageField(blank=True, help_text='Secondary photo for this event class', null=True, upload_to='event_classes/'),
        ),
    ]
