# Generated by Django 5.2.5 on 2025-08-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventclass_photo1_eventclass_photo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the venue', max_length=200)),
                ('address', models.TextField(help_text='Full address of the venue')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity of the venue', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the venue and its facilities')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number for the venue', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for the venue', max_length=254)),
                ('photo1', models.ImageField(blank=True, help_text='Primary photo of the venue', null=True, upload_to='venues/')),
                ('photo2', models.ImageField(blank=True, help_text='Secondary photo of the venue', null=True, upload_to='venues/')),
                ('photo3', models.ImageField(blank=True, help_text='Third photo of the venue', null=True, upload_to='venues/')),
                ('photo4', models.ImageField(blank=True, help_text='Fourth photo of the venue', null=True, upload_to='venues/')),
                ('photo5', models.ImageField(blank=True, help_text='Fifth photo of the venue', null=True, upload_to='venues/')),
                ('photo6', models.ImageField(blank=True, help_text='Sixth photo of the venue', null=True, upload_to='venues/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this venue is available for bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
            },
        ),
    ]
