# Generated by Django 5.2.5 on 2025-08-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitypool', '0003_individuals_photo_organizations_logo'),
        ('events', '0006_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['venue'], 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='venue',
            name='guy_in_charge',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this venue', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entitypool.individuals'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this event class', null=True),
        ),
    ]
