# Generated by Django 5.2.5 on 2025-08-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_venue_options_rename_name_venue_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_participants_lowerbound',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum expected number of participants', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_participants_upperbound',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum expected number of participants', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Venue where the event will be held', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venue'),
        ),
    ]
