# Generated by Django 5.2.5 on 2025-08-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_location_remove_event_max_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', help_text='Current status of the event schedule', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed event description', null=True),
        ),
    ]
