# Generated by Django 5.2.5 on 2025-08-16 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteOperatingModels',
            fields=[
                ('model_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('is_shared', models.BooleanField(default=False)),
                ('pricing_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Suite Operating Model',
                'verbose_name_plural': 'Suite Operating Models',
            },
        ),
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('suite_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('suite_number', models.CharField(max_length=20)),
                ('floor_plan', models.TextField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suite',
                'verbose_name_plural': 'Suites',
            },
        ),
        migrations.CreateModel(
            name='SuiteContracts',
            fields=[
                ('roe_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entity_id', models.PositiveIntegerField()),
                ('roe_begin', models.DateTimeField()),
                ('roe_end', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_suites.suiteoperatingmodels')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_suites.suites')),
            ],
            options={
                'verbose_name': 'Suite Contract',
                'verbose_name_plural': 'Suite Contracts',
            },
        ),
    ]
