# Generated by Django 5.2.5 on 2025-08-16 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_suites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suites',
            name='features',
        ),
        migrations.RemoveField(
            model_name='suites',
            name='photos',
        ),
        migrations.AddField(
            model_name='suites',
            name='corner_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suites',
            name='filing_cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suites',
            name='height_adjustible_desk',
            field=models.IntegerField(default=0, help_text='Number of height adjustable desks'),
        ),
        migrations.AddField(
            model_name='suites',
            name='minifridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suites',
            name='office_chairs',
            field=models.IntegerField(default=0, help_text='Number of office chairs'),
        ),
        migrations.AddField(
            model_name='suites',
            name='whiteboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suites',
            name='floor_plan',
            field=models.FileField(blank=True, help_text='Upload PDF floor plan', null=True, upload_to='suite_floorplans/'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SuitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='suite_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_photos', to='manage_suites.suites')),
            ],
            options={
                'verbose_name': 'Suite Photo',
                'verbose_name_plural': 'Suite Photos',
            },
        ),
    ]
