# Generated by Django 5.2.5 on 2025-08-16 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_suites', '0002_remove_suites_features_remove_suites_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiteoperatingmodels',
            name='pricing_info',
        ),
        migrations.AddField(
            model_name='suiteoperatingmodels',
            name='period',
            field=models.DurationField(default=datetime.timedelta(days=30), help_text='Time period for the pricing (e.g., monthly, weekly)'),
        ),
        migrations.AddField(
            model_name='suiteoperatingmodels',
            name='pricepoint',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in dollars', max_digits=10),
        ),
        migrations.AlterField(
            model_name='suiteoperatingmodels',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
