# Generated by Django 5.2.5 on 2025-08-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_suites', '0003_remove_suiteoperatingmodels_pricing_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteoperatingmodels',
            name='period',
            field=models.IntegerField(default=180, help_text='Time period in days for the pricing'),
        ),
        migrations.AlterField(
            model_name='suiteoperatingmodels',
            name='pricepoint',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Price in dollars', max_digits=10),
        ),
    ]
