# Generated by Django 5.2.5 on 2025-08-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitypool', '0002_individuals_email_alter_individuals_key_id_and_more'),
        ('manage_suites', '0004_alter_suiteoperatingmodels_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitecontracts',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='suitecontracts',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='suitecontracts',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitypool.individuals'),
        ),
        migrations.AddField(
            model_name='suitecontracts',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitypool.organizations'),
        ),
        migrations.AlterField(
            model_name='suitecontracts',
            name='roe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
