# Generated by Django 5.2.5 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_suites', '0005_remove_suitecontracts_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitecontracts',
            name='on_going',
            field=models.BooleanField(default=False, help_text='Check if this is an ongoing contract (no end date)'),
        ),
        migrations.AlterField(
            model_name='suitecontracts',
            name='roe_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suitecontracts',
            name='roe_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
