# Generated by Django 5.2.5 on 2025-08-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('ui_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(max_length=100)),
                ('name_last', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('rf_id', models.CharField(max_length=100)),
                ('key_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('uo_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_ein', models.CharField(max_length=20)),
                ('organization_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
