# Generated by Django 5.2.5 on 2025-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitypool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuals',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='rf_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
