# Generated by Django 5.2.5 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitypool', '0002_individuals_email_alter_individuals_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuals',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload individual photo', null=True, upload_to='individual_photos/'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload organization logo', null=True, upload_to='organization_logos/'),
        ),
    ]
